DROP DATABASE IF EXISTS employeesDB;

CREATE DATABASE employeesDB;


USE employeesDB;


CREATE TABLE department (
  id INTEGER(100) AUTO_INCREMENT NOT NULL,
  title VARCHAR(30) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE roles (
  id INTEGER(100) AUTO_INCREMENT NOT NULL,
  title VARCHAR(30) NOT NULL,
  salary DECIMAL NOT NULL,
  department_id INT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE employees (
  id INTEGER(100) AUTO_INCREMENT NOT NULL,
  first_name VARCHAR(30) NOT NULL,
  second_name VARCHAR(30) NOT NULL,
  role_id INT NOT NULL,
  manager_id INT NOT NULL,
  PRIMARY KEY (id)
);


